config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#new'


  resources :questions do
    resources :answers, only: [:index, :show, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :user_id, presence: true
  validates :question_id, presence: true
  validates :body, length: {minimum: 20}

  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 20}
  validates :user_id, presence: true

  belongs_to :user
  has_many :answers
end

app/models/user.rb
# class User < ApplicationRecord
#   validates :user_name, presence: true
#   validates :email, presence: true
#
#
#   has_many :answers
#   has_many :questions

class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question

    if @answer.save
      redirect_to @question
      flash[:notice] = "Thanks for the response!"
    else
      redirect_to @question
      flash[:notice] = @answer.errors.full_messages.to_sentence
    end
  end


private

def answer_params
  params.require(:answer).permit(:body, :user_id)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_owner?

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end

  def authenticate_user!
    if current_user.nil?
      flash[:notice] = "You gotta be signed in"
      redirect_to root_path
    end
  end

  def authenticate_owner!(resource)
    if !is_owner?(resource)
      flash[:notice] = "You gotta be the owner"
      redirect_to root_path
    end
  end

  def is_owner?(resource)
    current_user == resource.user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @questions = Question.order("created_at DESC").all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question
      flash[:notice] = "Question Submitted!"
    else
      flash[:notice] = @question.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    authenticate_owner!(@question)
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)

    redirect_to @question
  end

  def destroy
      @question = Question.find(params[:id])
      @question.destroy
      redirect_to action: "index"
  end


  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation-float.css">
  </head>

  <body class="page">
    <div class="top-page">
      <h1>SlackOverview 2.0<h1>
      <% if current_user.blank? %>
        <h6>Please Sign In</h6>
        <%= link_to 'Sign In with Github', '/auth/github' %>
        <% else %>
        <h6>
          You are signed in as <%= current_user.username %>.  Click the button below to sign out.
        </h6>

        <%= button_to "Sign Out", signout_path, method: :delete %>
          <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<div class="form">
<h1>Edit the Question</h1>


<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<div class="footer">
<%= link_to "Delete this Question", @question, :method => 'delete' %>
</div>

app/views/questions/index.html.erb
<h5> Recent Questions: </h5>
<%@questions.each do |question|%>
<ul>
  <li>
    <%= link_to question.title, question_path(question.id) %>
  </li>
</ul>
<%end%>

<div class="footer">
  <% if current_user == nil %>
    Please sign in to ask a question
  <% else %>
    <%= link_to "Ask Something New", new_question_path %>
  <%end%>
</div>

app/views/questions/new.html.erb
<div class="form">
  <h1>Ask a New Question!</h1>
  <p id="notice"><%= notice %></p>
<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<div class="footer">
<%= link_to "Return to Main page", questions_path%>
</div>

app/views/questions/show.html.erb
<div class="page">

<h1><%= @question.title %> </h1>
<h6> Asked by: <%= @question.user.username %> </h6> <br>
<h3 class="categorys"> Description: </h3>
<h4><%= @question.body %></h4>
<br>

  <h4 class="categorys"> Answers: </h4>
<ul class="white-background">
  <% @answers.each do |answer| %>
  <li>
     <%= answer.body %>
     - <%= answer.user.username  %>
   </li>
   <%end%>
</ul>
</div>

<div class="form">
<p id="notice"><%= notice %></p>
  <h2>Know a Solution?<h2>
  <%= form_for [@question, @answer] do |f| %>
    <div class="field">
      <%= f.label :body,"Enter a Solution" %>
      <%= f.text_field :body %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  <br>
</div>

<div class="footer">

<%= link_to 'Back to Home', questions_path %>

<% if is_owner?(@question) %>
  / <%= link_to 'Edit question', edit_question_path%> /
  <%= link_to "Delete this Question", @question, :method => 'delete' %>
<%end %>
</div>